#!/bin/bash

HostName=`hostname`

if [ $# -gt 0 ];then
    for disk in $@; do
        echo "$disk";
        pvcreate $disk -y;
        vgextend centos $disk;
        lvextend -l 100%PVS /dev/centos/root;
        xfs_growfs /
        if [ $? -gt 0 ]; then send-service-report "$HostName:cinder-nfs:failed:user $disk extend nfs failed"; exit 1;fi
    done
else
    exit 1
fi
