#!/bin/bash

if [ $# -lt 1 ]; then
    echo "error.. need args"
    exit 1
fi

DeployHostIp=`grep "master.server.com" /etc/hosts | awk '{print $1}'`

python /usr/local/include/tsTclnt.py $DeployHostIp $1
