#!/usr/bin/bash

source /etc/openstack.cfg

rpm -q net-snmap &>/dev/null || yum install net-snmp -y

rpm -q snmp-util &>/dev/null || yum install net-snmp-utils -y

echo "Stop snmpd service"
systemctl status snmpd &> /dev/null && systemctl stop snmpd

SNMP_CONFIG_DIR=/etc/snmp-bak/
echo "Reset config file"
if [ -d "$SNMP_CONFIG_DIR" ]; then
    cp -rf $SNMP_CONFIG_DIR /etc/ ;
else
    mkdir -pv $SNMP_CONFIG_DIR;
    cp -rf /etc/snmp $SNMP_CONFIG_DIR;
fi

sed -i "s/com2sec notConfigUser  default       public/com2sec notConfigUser  $CONTROLLER_NODE_IP       public/g" /etc/snmp/snmpd.conf

sed -i "s/access  notConfigGroup \"\"      any       noauth    exact  systemview none none/access  notConfigGroup \"\"      any       noauth    exact  all none none/g" /etc/snmp/snmpd.conf

sed -i "s/#view all    included  .1                               80/view all    included  .1                               80/g" /etc/snmp/snmpd.conf

sed -i 's/# disk checks/disk checks/g' /etc/snmp/snmpd.conf
sed -i 's/# disk \/ 10000/disk \/ 10000/g' /etc/snmp/snmpd.conf

systemctl enable snmpd
systemctl restart snmpd
systemctl status snmpd
if [ $? -gt 0 ]; then send-service-report "$HostName:mongod:failed:start snmpd service failed"; exit 1;fi
#snmpwalk -v 1 $HOSTIP -c public .1.3.6.1.4.1.2021.9

if [ $? -gt 0 ];
 then 
     echo "Get host disk information faill"
fi

send-service-report "$HostName:snmpd:success"
