#!/bin/bash

source /etc/openstack.cfg
HostName=`hostname`
THISHOST_IP=`facter | grep ipaddress_$MANAGE_NETWORKCARD_NAME | awk '{print $3}'`

#Stop all service
echo "Stop neutron server service"
systemctl status neutron-server.service &> /dev/null && systemctl stop neutron-server.service

#Delete databases
echo "Delete neutron databases"
if [ "$THISHOST_IP" == "$MARIADB_NODE_IP" ]; then
    mysql -u root <<EOF
DROP DATABASE neutron;
FLUSH PRIVILEGES;
EOF
else
    mysql -h $MARIADB_NODE_IP -u root -p$MARIADB_USER_PASS<<EOF
DROP DATABASE neutron;
FLUSH PRIVILEGES;
EOF
fi

OPENSTACK_SERVICE_CONFIG_DIR=/etc/openstack/service
OPENSTACK_NEUTRON_CONFIG_DIR=/etc/openstack/service/neutron
#Reset Neutron Config File
echo "Reset Neutron config file"
if [ -d "$OPENSTACK_NEUTRON_CONFIG_DIR" ]; then
    cp -rf $OPENSTACK_NEUTRON_CONFIG_DIR /etc/ ;
else
    mkdir -pv $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/neutron $OPENSTACK_SERVICE_CONFIG_DIR;
fi



















