#!/bin/bash

source /etc/openstack.cfg

#Stop all service
echo "Stop All Service"
echo "Stop ntp service"
systemctl stop ntpd.service

echo "Stop openstack-keystone service"
systemctl stop openstack-keystone.service

echo "Stop openstack-glance service"
systemctl stop openstack-glance-api.service openstack-glance-registry.service

echo "Stop openstack-nova-api service"
systemctl stop openstack-nova-api.service

echo "Stop openstack-nova-consoleauth service"
systemctl stop openstack-nova-consoleauth.service

echo "Stop openstack-nova-cert service"
systemctl stop openstack-nova-cert.service

echo "Stop openstack-nova-scheduler service"
systemctl stop openstack-nova-scheduler.service

echo "Stop openstack-nova-conductor service"
systemctl stop openstack-nova-conductor.service

echo "Stop openstack-nova-novncproxy service"
systemctl stop openstack-nova-novncproxy.service

echo "Stop neutron server service"
systemctl start neutron-server.service

echo "Stop http service"
systemctl stop httpd.service

echo "Stop memcached service"
systemctl stop memcached.service

echo "Stop cinder service"
systemctl stop openstack-cinder-api.service openstack-cinder-scheduler.service


#Delete databases
echo "Delete all databases"
mysql -h $MARIADB_NODE_IP -u root -p$MARIADB_USER_PASS<<EOF
DROP DATABASE keystone;
DROP DATABASE neutron;
DROP DATABASE glance;
DROP DATABASE nova;
DROP DATABASE cinder;
FLUSH PRIVILEGES;
EOF

OPENSTACK_SERVICE_CONFIG_DIR=/etc/openstack/service/
#Reset All Config File
echo "Reset all config file"
if [ -d "$OPENSTACK_SERVICE_CONFIG_DIR" ]; then
    cp -rf $OPENSTACK_SERVICE_CONFIG_DIR/* /etc/ ;
else
    mkdir -pv $OPENSTACK_SERVICE_CONFIG_DIR/openstack-dashboard;
    cp -rf /etc/nova $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/keystone $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/neutron $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/glance $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/cinder $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/ntp.conf $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/openstack-dashboard/* $OPENSTACK_SERVICE_CONFIG_DIR/openstack-dashboard/;
fi


















