#!/bin/bash

source /etc/openstack.cfg

#Delete the openvswitch bridge
echo "Delete the openvswitch bridge"
ovs-vsctl del-br br-ex
ovs-vsctl del-br br-int
ovs-vsctl del-br br-tun
ovs-vsctl del-br br-eth1

echo "Stop neutron service"
systemctl status neutron-l3-agent.service &> /dev/null && systemctl stop neutron-l3-agent.service
systemctl status neutron-dhcp-agent.service &> /dev/null && systemctl stop neutron-dhcp-agent.service
systemctl status neutron-metadata-agent.service &> /dev/null && systemctl stop neutron-metadata-agent.service
systemctl status openvswitch.service &> /dev/null && systemctl stop openvswitch.service
systemctl status neutron-openvswitch-agent.service &> /dev/null && systemctl stop neutron-openvswitch-agent.service

if [ $# -gt 0 -a "$1" == "allinone" ];then
    systemctl status neutron-server.service &> /dev/null && systemctl stop neutron-server.service
    #Delete databases
    echo "Delete neutron databases"
    if [ "$THISHOST_IP" == "$MARIADB_NODE_IP" ]; then
        mysql -u root <<EOF
DROP DATABASE neutron;
FLUSH PRIVILEGES;
EOF
    else
        mysql -h $MARIADB_NODE_IP -u root -p$MARIADB_USER_PASS<<EOF
DROP DATABASE neutron;
FLUSH PRIVILEGES;
EOF
    fi
fi

OPENSTACK_SERVICE_CONFIG_DIR=/etc/openstack/service
OPENSTACK_NEUTRON_CONFIG_DIR=/etc/openstack/service/neutron
#Reset Neutron Config File
echo "Reset neutron config file"
if [ -d "$OPENSTACK_NEUTRON_CONFIG_DIR" ]; then
    cp -rf $OPENSTACK_NEUTRON_CONFIG_DIR /etc/ ;
else
    mkdir -pv $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/neutron $OPENSTACK_SERVICE_CONFIG_DIR;
fi



