#!/bin/bash

source /etc/openstack.cfg

#Stop all service
echo "Stop All Service"

echo "Stop cinder volume service"
systemctl status openstack-cinder-volume.service && systemctl stop openstack-cinder-volume.service
systemctl status target.service && systemctl stop target.service

OPENSTACK_SERVICE_CONFIG_DIR=/etc/openstack/service
OPENSTACK_CINDER_CONFIG_DIR=/etc/openstack/service/cinder
#Reset Glance Config File
echo "Reset cinder config file"
if [ -d "$OPENSTACK_CINDER_CONFIG_DIR" ]; then
    cp -rf $OPENSTACK_CINDER_CONFIG_DIR /etc/ ;
else
    mkdir -pv $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/glance $OPENSTACK_SERVICE_CONFIG_DIR;
fi



