#!/bin/bash

source /etc/openstack.cfg

echo "Stop openstack compute service"
systemctl status libvirtd.service &> /dev/null && systemctl stop libvirtd.service
systemctl status openstack-nova-compute.service &> /dev/null && systemctl stop openstack-nova-compute.service

systemctl status openvswitch.service &> /dev/null && systemctl stop openvswitch.service
systemctl status neutron-openvswitch-agent.service &> /dev/null && systemctl stop neutron-openvswitch-agent.service
systemctl status neutron-dhcp-agent.service &> /dev/null && systemctl stop neutron-dhcp-agent.service

systemctl status openstack-ceilometer-compute.service &> /dev/null && systemctl stop openstack-ceilometer-compute.service

OPENSTACK_SERVICE_CONFIG_DIR=/etc/openstack/service
OPENSTACK_NOVA_CONFIG_DIR=/etc/openstack/service/nova
OPENSTACK_NEUTRON_CONFIG_DIR=/etc/openstack/service/neutron
OPENSTACK_CEILOMETER_CONFIG_DIR=/etc/openstack/service/ceilometer
#Reset Nova and Neutron Config File
echo "Reset config file"
if [ -d "$OPENSTACK_NOVA_CONFIG_DIR" ]; then
    cp -rf $OPENSTACK_NOVA_CONFIG_DIR /etc/ ;
    cp -rf $OPENSTACK_NEUTRON_CONFIG_DIR /etc/ ;
    cp -rf $OPENSTACK_CEILOMETER_CONFIG_DIR /etc/ ;
else
    mkdir -pv $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/nova $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/neutron $OPENSTACK_SERVICE_CONFIG_DIR;
    cp -rf /etc/ceilometer $OPENSTACK_CEILOMETER_CONFIG_DIR
fi



